//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiGrpcClient.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiGrpcClient.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC&apos;s File System.
        /// </summary>
        internal static string FileSystemPage {
            get {
                return ResourceManager.GetString("FileSystemPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC Files.
        /// </summary>
        internal static string MenuFiles {
            get {
                return ResourceManager.GetString("MenuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change language:.
        /// </summary>
        internal static string MenuLangTitle {
            get {
                return ResourceManager.GetString("MenuLangTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC condition.
        /// </summary>
        internal static string MenuPcStatus {
            get {
                return ResourceManager.GetString("MenuPcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Running programms.
        /// </summary>
        internal static string MenuRunProgs {
            get {
                return ResourceManager.GetString("MenuRunProgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitors.
        /// </summary>
        internal static string MenuScreens {
            get {
                return ResourceManager.GetString("MenuScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Soudns settings.
        /// </summary>
        internal static string MenuSound {
            get {
                return ResourceManager.GetString("MenuSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battary/Work Time.
        /// </summary>
        internal static string pcStatusBattaryLoad {
            get {
                return ResourceManager.GetString("pcStatusBattaryLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU.
        /// </summary>
        internal static string pcStatusCPU {
            get {
                return ResourceManager.GetString("pcStatusCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last pc&apos;s request.
        /// </summary>
        internal static string pcStatusLastRequest {
            get {
                return ResourceManager.GetString("pcStatusLastRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAM.
        /// </summary>
        internal static string pcStatusRam {
            get {
                return ResourceManager.GetString("pcStatusRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pc status.
        /// </summary>
        internal static string pcStatusTitle {
            get {
                return ResourceManager.GetString("pcStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processes.
        /// </summary>
        internal static string RunnigProgrammsPageTitle {
            get {
                return ResourceManager.GetString("RunnigProgrammsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitors.
        /// </summary>
        internal static string ScreensPageTitle {
            get {
                return ResourceManager.GetString("ScreensPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound devices.
        /// </summary>
        internal static string SoundPageCheckerTitle {
            get {
                return ResourceManager.GetString("SoundPageCheckerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This choice affects both input and output devices. The change will depend on the choice, selecting an input device will change only the input device, and selecting an output device will change only the output device..
        /// </summary>
        internal static string SoundPageDescription {
            get {
                return ResourceManager.GetString("SoundPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound.
        /// </summary>
        internal static string SoundPageTitle {
            get {
                return ResourceManager.GetString("SoundPageTitle", resourceCulture);
            }
        }
    }
}
